language: node_js
node_js:
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database collaboard_test;' -U postgres
  - NODE_ENV=test npm run migrate
script:
  - npm run lint
  - npm test
